DROP TABLE IF EXISTS ReplyPosts;
DROP TABLE IF EXISTS TimelinePosts;
DROP TABLE IF EXISTS Replies;
DROP TABLE IF EXISTS Topics;
DROP TABLE IF EXISTS Forums;
DROP TABLE IF EXISTS Persons;
DROP TABLE IF EXISTS [__EFMigrationsHistory];

GO
