DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS StoreItems;
DROP TABLE IF EXISTS Stores;
DROP TABLE IF EXISTS BlogComments;
DROP TABLE IF EXISTS Blogs;
DROP TABLE IF EXISTS Friends;
DROP TABLE IF EXISTS ReplyPosts;
DROP TABLE IF EXISTS WallPosts;
DROP TABLE IF EXISTS Replies;
DROP TABLE IF EXISTS Topics;
DROP TABLE IF EXISTS Forums;
DROP TABLE IF EXISTS GroupMembers;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Persons;
DROP TABLE IF EXISTS [__EFMigrationsHistory];

GO
